[supervisord]
nodaemon=true
user=root

[program:backend]
command=gunicorn --bind 0.0.0.0:5000 app:app
directory=/app/backend
autostart=true
autorestart=true
stderr_logfile=/var/log/backend.err.log
stdout_logfile=/var/log/backend.out.log

[program:ml-service]
command=python app.py
directory=/app/ml-service
autostart=true
autorestart=true
stderr_logfile=/var/log/ml.err.log
stdout_logfile=/var/log/ml.out.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
