apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
  labels:
    app: grafana
data:
  grafana.ini: |
    [server]
    http_port = 3000
    # domain = localhost
    # root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
    # serve_from_sub_path = true

    [security]
    admin_user = admin
    admin_password = admin123
    allow_embedding = true

    [auth.anonymous]
    enabled = false

    [log]
    mode = console
    level = info

    [metrics]
    enabled = true

    [dashboards]
    versions_to_keep = 20

    [unified_alerting]
    enabled = true
